name: emg3d-gallery

channels:
  - conda-forge

dependencies:
  - "libblas=*=*mkl"
  - mamba
  - empymod
  - emg3d
  - xarray
  - discretize
  - h5py
  - matplotlib
  - memory_profiler
  - scooby
  - sphinx
  - sphinx-gallery
  - numpydoc
  - pooch
  - pydata-sphinx-theme
  - mkl-service
